version: '3.3'
services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    networks:
      - monitorWebNet
  portainer:
    image: portainer/portainer:latest
    ports:
     - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    networks:
      - monitorWebNet

volumes:
  portainerdata:

networks:
  monitorWebNet:

